CREATE TABLE COLABORADORES(
    CODIGO VARCHAR(5),
    NOME VARCHAR(80),
    DEPARTAMENTO INT,
    SALARIO MONEY
)
GO

CREATE PROCEDURE Salario_Depto(
    @DEPTO INT,
    @SOMA MONEY OUTPUT
)
AS
BEGIN
    SELECT @SOMA = SUM(SALARIO)
    FROM
        COLABORADORES
    WHERE
        DEPARTAMENTO = @DEPTO
END

DECLARE @SALARIO_TOTAL MONEY
DECLARE @DEPARTAMENTO INT
SET @DEPARTAMENTO = 5
EXEC Salario_Depto @DEPARTAMENTO, @SALARIO_TOTAL OUTPUT
PRINT @SALARIO_TOTAL